# Meltano Configuration File
# 
# One-time workstation setup:
# > meltano install  # Install the plugins declared by the project
#
# Sample usage for end-to-end development:
# > meltano run el    # Run the job titled 'el' to extract and load data
# > meltano run t     # Run the job titled 't' to transform data
# > meltano run bi    # Build and serve the Evidence BI reports
#
# Repeat the same actions as above on "prod":
# > meltano --environment=prod run elt evidence:build

version: 1
project_id: bd6709c7-2d8b-4aba-9697-f6cd61582e74  # Unique ID for Jaffle Shop Template
jobs:
  # Sample usage:  `meltano run el`
  # Equivalent to: `meltano run tap-jaffle-shop target-duckdb`
- name: el         # Extract and load the raw data
  tasks:
  - tap-jaffle-shop target-duckdb

default_environment: dev
env:
  JAFFLE_DB_NAME: jaffle_shop
  JAFFLE_RAW_SCHEMA: tap_jaffle_shop
environments:
- name: dev
  env:
    TAP_JAFFLE_SHOP_YEARS: '1'
    JAFFLE_DB_PATH: ${MELTANO_PROJECT_ROOT}/reports/jaffle_shop.duckdb
- name: staging
  env:
    TAP_JAFFLE_SHOP_YEARS: '3'
    JAFFLE_DB_PATH: ${MELTANO_PROJECT_ROOT}/reports/jaffle_shop.${MELTANO_ENVIRONMENT}-duckdb
- name: prod
  env:
    TAP_JAFFLE_SHOP_YEARS: '5'
    JAFFLE_DB_PATH: ${MELTANO_PROJECT_ROOT}/reports/jaffle_shop.${MELTANO_ENVIRONMENT}-duckdb

plugins:
  extractors:
  - name: tap-jaffle-shop
    namespace: tap_jaffle_shop
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-jaffle-shop.git@v0.2.1
    capabilities:
    - catalog
    - discover
    config:
      years: 1
      stream_name_prefix: ${JAFFLE_RAW_SCHEMA}-raw_
  loaders:
  - name: target-duckdb
    variant: jwills
    pip_url: target-duckdb~=0.4
    config:
      filepath: ${JAFFLE_DB_PATH}
