name: CI

on: pull_request

jobs:
  dbt-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python -m pip install -r requirements.txt
      - run: dbt deps
      - run: dbt build
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd reports && npm install && npm run build
      # TODO: Retest after: https://github.com/evidence-dev/evidence/issues/682
      #- run: cd reports && npm install && npm run build:strict
