name: CI

on: pull_request

jobs:
  extract-and-load:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: meltano install
      - run: meltano run tap-jaffle-shop target-duckdb

  dbt-build:
    runs-on: ubuntu-22.04
    needs: [extract-and-load]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python -m pip install -r requirements.txt
      - run: dbt deps
      - run: dbt build
