name: CI

on: [pull_request]

jobs:
  e2e-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Meltano
        run: pipx install meltano
      - name: Install dbt and other tools
        run: meltano install
      - name: Extract and Load
        run: meltano run el
      - name: Transform
        run: meltano invoke dbt-duckdb:build
      - name: Upload DuckDB database artifact
        uses: actions/upload-artifact@v1
        if: always()
        with:
          path: 'reports/jaffle_shop.dev-duckdb'
          name: ci-build.duckdb
      - name: Build BI reports
        run: meltano invoke evidence:build-strict
      - name: Upload BI reports artifact
        uses: actions/upload-artifact@v1
        with:
          path: 'reports/build'
          name: ci-build.duckdb
